name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - Mara-Li
body:
 - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
 - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "Tell us what you see! And don't forget the error"
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: repro-bug
    attributes:
      label: How to reproduce ?
      description: Step to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error 
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. You can open the Obsidian's console with "CTRL+MAJ+I"
      render: shell
  - type: dropdown
    id: version
    attributes:
      label: OS
      description: What OS do you use ? 
      multiple: true
      options:
        - IOS
        - Android
        - MacOS
        - Windows
        - Linux
    validations:
      required: true
  - type: textarea
    attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  
