name: Question 
description: I have a question!
title: "[Q]: "
labels: ["question"]
assignees:
  - Mara-Li
body:
  - type: checkboxes
    label: Issue validation
    description: "Thanks to check if your question is relative to the repository. Any non-relative or duplicate will be closed."
    options:
      - label: "My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)"
        required: true
      - label: "I checked the issue to prevent duplicate"
        required: true
      - label: "I checked the documentation of Material Mkdocs, Mkdocs and the Obsidian Publisher template"
        required: true
  - type: dropdown
    attributes:
      label: My question concern... (please, choose bellow)
      multiple: true
      options:
        - The Obsidian Publisher template 🗃️
        - The Python package 🐍
        - The Obsidian Plugin 💠
        - I don't know 😿
    validations:
      required: true
  - type: textarea
    attributes:
      label: My question!
      description: |
        A clear and concise description of your question.
        *Tip* : You can attach images or log files by clicking this aera to highlight it and then dragging files in!
      placeholder: Be gentle!
    validations:
      required: true
