name: Manually release

on:
  workflow_dispatch

env:
    PLUGIN_NAME: obsidian-metacopy # Change this to match the id of your plugin.

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "14.x"

            - name: Build
              id: build
              run: |
                  git config --global user.name 'github-release'
                  git config --global user.email 'github-release@users.noreply.github.com' 
                  npm install
                  npm run release
                  git push --follow-tags origin master
